apiVersion: sonataflow.org/v1alpha08
kind: SonataFlow
metadata:
  name: ${{ values.workflowId }}
  annotations:
    sonataflow.org/profile: gitops
  labels:
    backstage.io/kubernetes-id: ${{ values.workflowId }}
spec:
  persistence:
    postgresql:
      secretRef:
        name: ${{ values.persistencePSQLSecretName }}
        userKey: ${{ values.persistencePSQLUserKey }}
        passwordKey: ${{ values.persistencePSQLPasswordKey }}
      serviceRef:
        name: ${{ values.persistencePSQLServiceName }}
        namespace: ${{ values.persistencePSQLServiceNamespace }}
        port: ${{ values.persistencePSQLServicePort }}
        databaseName: ${{ values.persistencePSQLDatabaseName }}
        databaseSchema: ${{ values.persistencePSQLDatabaseSchema }}
  podTemplate:
    container:
      image: serverless-workflow-${{ values.workflowId }}
      envFrom:
        - configMapRef:
            name: ${{ values.workflowId }}-gitops
        - secretRef:
            name: ${{ values.workflowId }}-secret
      resources: {}
