apiVersion: sonataflow.org/v1alpha08
kind: SonataFlow
metadata:
  name: ${{ values.workflowId }}
  annotations:
    sonataflow.org/profile: prod
  labels:
    backstage.io/kubernetes-id: ${{ values.workflowId }}
spec:
  podTemplate:
    container:
      image: serverless-workflow-${{ values.workflowId }}
      envFrom:
      - configMapRef:
          name: ${{ values.workflowId }}-gitops
      - secretRef:
          name: ${{ values.workflowId }}-secret
      resources: {}
