# From https://github.com/redhat-developer/red-hat-developer-hub-software-templates/blob/main/skeletons/tekton/tekton/route.yaml
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: webhook-${{ values.workflowId }}-el
  namespace: ${{ values.namespace }}
  labels:
    app.kubernetes.io/managed-by: EventListener
    app.kubernetes.io/part-of: Triggers
    eventlistener: ${{ values.repoName }}-el
spec:
  to:
    kind: Service
    name: el-${{ values.workflowId }}-el
    weight: 100
  port:
    targetPort: http-listener
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
