---
openapi: 3.1.0
info:
  title: serverless-workflow-precheck API
  version: 1.0.0-SNAPSHOT
tags:
- name: preCheck
paths:
  /preCheck:
    post:
      tags:
      - preCheck
      summary: preCheck
      description: ""
      operationId: createResource_preCheck
      parameters:
      - name: businessKey
        in: query
        schema:
          default: ""
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/JsonNodeModelInput'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JsonNodeModelInput'
components:
  schemas:
    JsonNodeModelInput:
      type: object
      properties:
        workflowdata:
          type: object
