apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.workflowId }}-gitops
  description: ${{ values.description }}
  annotations:
    argocd/app-selector: rht-gitops.com/janus-argocd=${{ values.workflowId }}-gitops
    backstage.io/kubernetes-label-selector: 'app=${{ values.workflowId }},sonataflow.org/workflow-app=${{ values.workflowId }}'
    backstage.io/kubernetes-namespace: ${{ values.namespace }}
    backstage.io/kubernetes-id: ${{ values.workflowId }}
    github.com/project-slug: ${{ values.orgName }}/${{ values.repoName }}
    gitlab.com/project-slug: ${{ values.orgName }}/${{ values.repoName }}
spec:
  type: ${{ values.applicationType }}
  system: ${{ values.system }}
  lifecycle: ${{ values.lifecycle }}
  owner: ${{ values.owner }}
  dependsOn:
    - component:${{ values.workflowId }}
